name: heroku_deplo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi=0.63.0
  - uvicorn
  - gunicorn
  - pip=20.3.3
  - spyder-kernels=2.4
  - qt
  - pytest
  - matplotlib
  - pip:
    - ydata-profiling
    - pandas_dq
    - reportlab
    - PyPDF2
    - pdfreader
    - PyMuPDF
    - pdfrw

